### ISSUE TITLE
Training code release?

### ISSUE THREAD

**Issue by zc-alexfan** [NVlabs/dex-ycb-toolkit#3]
Is there goanna be a training code release for hand pose estimation?

Thanks

**Comment by ychao-nvidia** [comment]
No, there is no plan for that.

**Comment by trevor-taeyeop** [comment]
I am curious if there is any plan to provide training codes related to other estimations (2D detection, 6d object pose estimation).

**Comment by ychao-nvidia** [comment]
For 6D object pose, we have released the code for PoseCNN, DeepIM, and PoseRBPF:
https://github.com/NVlabs/PoseCNN-PyTorch#training-and-testing-on-the-dexycb-dataset
https://github.com/NVlabs/DeepIM-PyTorch#training-and-testing-on-the-dexycb-dataset
https://github.com/NVlabs/PoseRBPF#testing-on-the-dexycb-dataset

As mentioned in the [paper Sec. 5.3](https://dex-ycb.github.io/assets/chao_cvpr2021.pdf), we did not retrain PoseRBPF.

**Comment by ychao-nvidia** [comment]
"I understood that the 3D models and poses annotation of the existing YCB and YCB (bop) is slightly different, am I correct?"
-> Correct.

**Q1.** Can you please clarify with regards to your dataset(ycbdex) pose annotation and 3d models related to bop dataset?? (ex, dexycb annotation follows the original YCB or YCB(bop))
-> We provide both.

- The original 6D pose annotation we provide in `pose.npz` (e.g., loaded in the dex-ycb-toolkit API, such as [in this example](https://github.com/NVlabs/dex-ycb-toolkit#loading-dataset-and-visualizing-samples)) uses the [YCB-Video](https://rse-lab.cs.washington.edu/projects/posecnn/) models. If you download the DexYCB dataset, you can also find a copy of these models under `models/`.
- In addition, we also provide the 6D pose annotation using the [YCB-V (BOP)](https://bop.felk.cvut.cz/datasets/#YCB-V) models. This is stored under `bop/`. In fact, `bop/` is a copy of the full DexYCB dataset under the BOP format, which you can directly use with any methods that consume this format, e.g. [CosyPose](https://github.com/ylabbe/cosypose). If you look at `bop/models/` and `bop/models_eval/`, you'll find that these models are directly copied from [YCB-V (BOP](https://bop.felk.cvut.cz/datasets/#YCB-V)).

**Q2.** I want to check performance on dexycb dataset using pretrained CosyPose or PoseCNN trained from YCB or YCB(bop) without training dexycb dataset. Have you already tried this?? If yes, Can you share the results?? It would be really helpful.
-> We don't have pre-trained results. It should be possible to get that for PoseCNN using their released [repo](https://github.com/NVlabs/PoseCNN-PyTorch). You need to regenerate the results with the pre-trained model and then run eval (see [here](https://github.com/NVlabs/PoseCNN-PyTorch#training-and-testing-on-the-dexycb-dataset)).

**Q3.** Is there any reason a large clamp was removed compared to the YCB dataset??
-> We did not include `051_large_clamp` since it it sufficiently similar to `052_extra_large_clamp`.

**Comment by taeyeop-lee** [comment]
Thanks for the detailed reply!
