### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.eval_util' while testing examples/evaluate_hpe.py

### ISSUE THREAD

**Issue by Roopesh-Nallakshyam** [NVlabs/dex-ycb-toolkit#31]
I was trying to test HPE (Hand Pose Estimation) as mentioned in readme and getting below error
_python -m examples.evaluate_hpe.py 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "../codes/dex-ycb-toolkit/examples/evaluate_hpe.py", line 10, in <module>
    from dex_ycb_toolkit.hpe_eval import HPEEvaluator
  File "../codes/dex-ycb-toolkit/dex_ycb_toolkit/hpe_eval.py", line 21, in <module>
    from utils.eval_util import EvalUtil
ModuleNotFoundError: No module named 'utils.eval_util'_

I installed **utils** module as well using **pip install utils**. Could you please help me out here?

**Comment by ychao-nvidia** [comment]
`EvalUtil` is from the [freihand](https://github.com/ywchao/freihand/tree/b48ca4e1280c6b5c5562375ef34e97d984b487f6) submodule ([here](https://github.com/ywchao/freihand/blob/517e13ef6d995c9c24af3a42362140217a20c1df/utils/eval_util.py#L4)). Perhaps your `freihand/` folder is empty since you did not clone with `--recursive`. Beside re-cloning, you can also fetch the submodules with `git submodule update --init` under `dex-ycb-toolkit/`.

**Comment by Roopesh-Nallakshyam** [comment]
Thank you, it is working after cloning _freihand_  repo.
